name:                aoc2022
version:             2022.0
github:              "EthanWelsh/aoc2022"
author:              "Ethan Welsh"

extra-source-files:
- README.md

description:         Ethan's solutions to Advent of Code 2022

dependencies:
- base >= 4.7 && < 5
- search-algorithms
- time
- megaparsec
- range
- unordered-containers
- ansi-terminal
- directory
- optparse-applicative
- parser-combinators
- attoparsec
- containers
- text
- mtl
- vector

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedStrings
    - GADTs
    - GHC2021

executables:
  aoc-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -with-rtsopts=-qa
    - -with-rtsopts=-C0
    - -funfolding-use-threshold=16
    - -fexcess-precision
    - -optc-O3
    - -optc-ffast-math
    - -O2
    default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedStrings
    - GADTs
    - GHC2021
    dependencies:
    - aoc2022
